[build]
  command = "npm run build:netlify"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NEXT_WEBPACK_USEPOLLING = "1"
  NODE_OPTIONS = "--enable-source-maps"

[functions]
  node_bundler = "esbuild"
  external_node_modules = [
    "@nestjs/common",
    "@nestjs/core",
    "@nestjs/platform-express",
    "@nestjs/microservices",
    "@nestjs/websockets",
    "@nestjs/platform-socket.io",
    "class-transformer",
    "class-validator",
    "reflect-metadata",
    "rxjs"
  ]

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
